name: Print CI Environment

on:
  push: # or pull_request — whatever events you use
  pull_request:

jobs:
  debug_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dump all env variables
        run: env | sort
