# name of the workflow.
# this is optional.
name: Doc Tests

# events that will trigger this workflow.
# here, we only have "pull_request", so the workflow will run
# whenever we create a pull request.
# other examples: [push] and [pull_request, push]
on:
  pull_request:

  push:

# each workflow must have at least one job.
# jobs run in parallel by default (we can change that).
# each job groups together a series of steps to accomplish a purpose.
jobs:
  deploy:
    runs-on: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Skip push events for PRs
        run: |
          if [ "$FORGEJO_EVENT_NAME" = "push" ] && [[ "$FORGEJO_REF" != refs/heads/* ]]; then
            echo "Skipping steps for push that is part of a PR"
            exit 0
          fi

      - name: Check
        run: cargo check

      - name: Doc Tests
        run: cargo test --doc --no-fail-fast --quiet
