# name of the workflow.
# this is optional.
name: Doc Tests

# events that will trigger this workflow.
# here, we only have "pull_request", so the workflow will run
# whenever we create a pull request.
# other examples: [push] and [pull_request, push]
on:
  pull_request:

  push:

# each workflow must have at least one job.
# jobs run in parallel by default (we can change that).
# each job groups together a series of steps to accomplish a purpose.
jobs:
  deploy:
    runs-on: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check
        if: env.CI_COMMIT_REF_NAME == 'master'
        run: cargo check

      - name: Doc Tests
        if: env.CI_COMMIT_REF_NAME == 'master'
        run: cargo test --doc --no-fail-fast --quiet
